# Generated by Django 4.0.2 on 2022-02-23 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_machine_delete_mytestjs_delete_testjs'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
